bounds:
  x: [0, 50] # x-bounds
  y: [0, 50] # y-bounds
  z: [0, 50] # z-bounds

obstacles:
  - type: box
    position: [10, 10, 1] # The 3D position of the obstacle in the environment
    size: [4, 4, 2] # The side lengths of the box-shaped obstacle
    rotation: [0, 0, 0]  # Euler angles in degrees
    color: red
    
  - type: cylinder
    endpoints: [[15, 10, 0], [15, 10, 15]] # The 3D endpoints of the cylinder
    radius: 2.5 # The radius of the cylinder in meters
    rotation: [0, 0, 0]
    color: red

  - type: sphere
    position: [5, 10, 2]
    radius: 2.0 # The radius of the sphere in meters
    color: red

  - type: box
    position: [18, 10, 1] # The 3D position of the obstacle in the environment
    size: [4, 4, 2] # The side lengths of the box-shaped obstacle
    rotation: [0, 0, 0]  # Euler angles in degrees
    color: red
    
goals:
  - position: [30, 30, 2] # The 3D position of the first goal
    radius: 1.0 # The radius of the first goal
  - position: [20, 30, 2] # The 3D position of the second goal
    radius: 1.0 # The radius of the second goal
